# Generated by Django 6.0.7 on 2026-07-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echographe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='echographes/photos/')),
                ('fiche_technique', models.FileField(blank=True, upload_to='echographes/fiches/')),
                ('bon_livraison', models.FileField(blank=True, upload_to='echographes/bons/')),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('garantie', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='echographes/qrcodes/')),
                ('prochaine_maintenance', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Échographe',
                'verbose_name_plural': 'Échographes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='QRImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_qr', models.TextField()),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import QR code',
                'verbose_name_plural': 'Imports QR code',
                'ordering': ['-date_scan'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], max_length=20)),
                ('date_intervention', models.DateField()),
                ('technicien', models.CharField(max_length=100)),
                ('panne', models.TextField(blank=True)),
                ('reparation', models.TextField(blank=True)),
                ('temps_arret', models.FloatField(default=0, help_text="Temps d'arrêt en heures")),
                ('echographe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='equipments.echographe')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('declaree', 'Déclarée'), ('en_cours', 'En cours de traitement'), ('resolue', 'Résolue')], default='declaree', max_length=20)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='equipments.echographe')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='equipments.fournisseur')),
            ],
            options={
                'verbose_name': 'Pièce de rechange',
                'verbose_name_plural': 'Pièces de rechange',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.CharField(max_length=100)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='equipments.piecerechange')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], max_length=20)),
                ('date_prevue', models.DateField()),
                ('technicien', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('echographe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='equipments.echographe')),
            ],
            options={
                'verbose_name': 'Planification de maintenance',
                'verbose_name_plural': 'Planifications de maintenance',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='equipments.etablissement')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='echographe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echographes', to='equipments.service'),
        ),
    ]
